services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: gen-ai-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'  # Exposing container port 5432 to host port 5432

